language: go

os:
  - linux
  - osx
  - windows

jobs:
  allow_failures:
    - os: osx

go:
  - 1.14.x

env:
  - GO111MODULE=on

before_install:
  - go get -v golang.org/x/lint/golint
  - go get github.com/spf13/cobra

script:
  - go build main.go