name: CI

on:
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Discord notification
      env:
        DISCORD_WEBHOOK: ${{ secrets.DISCORD_WEBHOOK }}
      uses: Ilshidur/action-discord@master
      with:
        args: |
          "{{ EVENT_PAYLOAD.sender.login }} has made a pull request on {{ EVENT_PAYLOAD.repository.name }}."
          "{{ EVENT_PAYLOAD.pull_request.base.label }} : {{ EVENT_PAYLOAD.pull_request.head.label }}"
          "{{ EVENT_PAYLOAD.pull_request.html_url }}"
