name: CI

on:
  pull_request:
    branches: [ master ]
    
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Discord notification
      env:
        DISCORD_WEBHOOK: ${{ secrets.DISCORD_WEBHOOK }}
      uses: Ilshidur/action-discord@master
      with:
        args: '''{{ EVENT_PAYLOAD.pusher.name }} has made a pull request on {{ EVENT_PAYLOAD.repository.full_name }}. 
        {{ EVENT_PAYLOAD.compare }}'''
